services:
  - type: web
    name: my-php-app
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: |
      composer install --no-dev
      php artisan migrate --force
      php artisan storage:link